# Site settings
title: ZenJedi
header-img: img/home-bg.jpg
email: lehung229@gmail.com
copyright_name: ZenJedi
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "https://zenjedi.github.io"
twitter_username: tonyhungle
github_username:  hungle90
facebook_username:  IronSummitMedia
email_username:  lehung229@gmail.com
# GH-pages supported plugins
gems:
  - jekyll-feed
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
# Build settings
highlighter: pygments
permalink: pretty
paginate: 5
gems: [jekyll-paginate]
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]